services:
  lightmancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # Backend URL is configured at build time via VITE_API_BASE
      # Default backend: https://lightmancerbackend.arturs.software
      # Alternative: https://lightmancerbackend.artur.engineer
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    restart: unless-stopped
    container_name: lightmancer-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lightmancer.rule=Host(`lightmancer.local`)"
      - "traefik.http.services.lightmancer.loadbalancer.server.port=80"

# Optional: Add reverse proxy for production deployment
#  nginx-proxy:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
#      - /path/to/ssl/certs:/etc/nginx/certs:ro
#    depends_on:
#      - lightmancer
#    restart: unless-stopped